name: Run a notebook in databricks on PRs

on:
 [push]

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         new-cluster-json: >
           {
             "cluster_name": "HGitCluster01",
             "num_workers": 1,
             "spark_version": "7.3.x-cpu-ml-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }